### ISSUE TITLE
Task 1 - CheckList

### ISSUE THREAD

**Issue by Damian2057** [Damian2057/concurrentProgramming#5]
- [ ] text is in C# and use .NET
- [ ] build succeeded
- [ ] all UT are green
- [ ] `Data` layer is clearly stated using language terms only (no database of file access is required)
- [ ] `Data` API is abstract
- [ ] `Logic` layer is clearly stated using language terms only
- [ ] `Logic` API is clearly stated
- [ ] `Logic` uses only the abstract `Data` layer API
- [ ] `Presentation` layer is clearly stated using language terms only
- [ ] mvvm and xaml is applied to implement GUI
- [ ] reactive and interactive user interaction for user (operator) communication
- [ ] reactive and interactive programming is used for layers communication
- [ ] Object model representing process data
- [ ] Unit Test - layers are tested independently using abstract API
- [ ] Dependency injection (additional framework is not required)
- [ ] Mock is used for testing purposes (expected but not required)
