### ISSUE TITLE
Task 2 - CheckList

### ISSUE THREAD

**Issue by Damian2057** [Damian2057/concurrentProgramming#9]
**-- Starting point**
- [x] all UT are green
- [x] the program behaves as expected (intermediate approval test)
**-- Data Layer**
- [x] responsibility of this layer is to represent boundaries of the movement rectangle and balls
- [x] balls representation are independent and self-contained (no timer required)
- [x] balls implementation uses parallel programming if applicable (depends on the run time platform)
**--  Logic Layer**
- [x] responsibility of this layer is to manage movement rectangle boundaries and balls interaction (collisions)
- [x] prove that the protection of data integration is implemented
- [x] Logic uses only the abstract Data layer API
**--  Presentation Layer (mvvm)**
-  [x] responsibility of this layer is to manage the graphical user interface (GUI)
-  [x] user => GUI interoperability must be implemented using interactive programming only
-  [x] GUI => the user interoperability must be implemented using reactive programming only (timer is not allowed)
-  [x] interoperability of the GUI and underlying layers must be synchronized
  **--  Testing**
- [x] Unit Test - layers are tested independently using dependency injection (additional framework is not required)
- [ ] Mock may be used for testing purpose (expected but not required)
